
# html lang
language: zh-cmn

# main menu navigation
menu:
  Home: /
  Archives: /archives
  Category: /category
  About: /about

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/500miles.css

# scripts loaded in the end of the body
scripts:
- /js/500miles.js
